### PR TITLE
Update translation files

### PR DESCRIPTION
**Pull request by cooljeanius**
This is basically just me running `wmlxgettext` and the various other gettext tools to bring the translation files up-to-date; N.B. I haven't tested to see if it actually works yet, though

### CODE REVIEW

**Comment by cooljeanius** [comment]
bumbadadadum is @Asheviere, right? (asking because the commit message for 1977fb3 says that this translation file originally came from bumbadadadum)

**Comment by Vultraz** [comment]
Yes, that's her.

**Comment by cooljeanius** [comment]
> Yes, that's her.

OK, I was just wondering if maybe she'd like to comment on the changes to the translation at all...

**Comment by Vultraz** [comment]
She hasn't been around in several years so it's doubtful.

**Pull request merged**
